version: "3.8"

services:
  postgres:
    image: postgres:17
    platform: linux/amd64
    container_name: postgres-local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: postgres -c max_connections=200 -c max_prepared_transactions=100
    volumes:
      - ../volumes/postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
