version: "3.8"

services:
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - ../volumes/redis-insight-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    external: true
    name: redis-local_redis-cluster-net
