version: "3.8"

services:
  mysql-local:
    image: mysql:8.0.37
    platform: linux/amd64
    container_name: mysql-local
    hostname: mysql-local
    ports:
      - "3339:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command:
      - "mysqld"
      - "--server-id=2"
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ../volumes/mysql-local-data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql-local-data:
    name: mysql-local-data
